In [1]:
import pandas as pd
import numpy as np

# Reading Data

In [2]:
train_x = pd.read_csv('../input/train_features.csv')
train_y_scored = pd.read_csv('../input/train_targets_scored.csv')
train_y_not_scored = pd.read_csv('../input/train_targets_nonscored.csv')
test_x = pd.read_csv('../input/test_features.csv')
sampe_sub = pd.read_csv('../input/sample_submission.csv')
train_x.head()

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,c-90,c-91,c-92,c-93,c-94,c-95,c-96,c-97,c-98,c-99
0,id_000644bb2,trt_cp,24,D1,1.0620,0.5577,-0.2479,-0.6208,-0.1944,-1.0120,...,0.2862,0.2584,0.8076,0.5523,-0.1912,0.6584,-0.3981,0.2139,0.3801,0.4176
1,id_000779bfc,trt_cp,72,D1,0.0743,0.4087,0.2991,0.0604,1.0190,0.5207,...,-0.4265,0.7543,0.4708,0.0230,0.2957,0.4899,0.1522,0.1241,0.6077,0.7371
2,id_000a6266a,trt_cp,48,D1,0.6280,0.5817,1.5540,-0.0764,-0.0323,1.2390,...,-0.7250,-0.6297,0.6103,0.0223,-1.3240,-0.3174,-0.6417,-0.2187,-1.4080,0.6931
3,id_0015fd391,trt_cp,48,D1,-0.5138,-0.2491,-0.2656,0.5288,4.0620,-0.8095,...,-2.0990,-0.6441,-5.6300,-1.3780,-0.8632,-1.2880,-1.6210,-0.8784,-0.3876,-0.8154
4,id_001626bd3,trt_cp,72,D2,-0.3254,-0.4009,0.9700,0.6919,1.4180,-0.8244,...,0.0042,0.0048,0.6670,1.0690,0.5523,-0.3031,0.1094,0.2885,-0.3786,0.7125

In [9]:
print(train_x.shape)
print(train_x.info())

(23814, 876)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23814 entries, 0 to 23813
Columns: 876 entries, sig_id to c-99
dtypes: float64(872), int64(1), object(3)
memory usage: 159.2+ MB
None

In [20]:
print(train_y_scored.shape)
print(train_y_not_scored.shape)

(23814, 207)
(23814, 403)

# Data Processing

In [3]:
# Combining train X and Y
df = pd.merge(train_x, train_y_scored, on = 'sig_id', how = 'left')
df.head()

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
0,id_000644bb2,trt_cp,24,D1,1.0620,0.5577,-0.2479,-0.6208,-0.1944,-1.0120,...,0,0,0,0,0,0,0,0,0,0
1,id_000779bfc,trt_cp,72,D1,0.0743,0.4087,0.2991,0.0604,1.0190,0.5207,...,0,0,0,0,0,0,0,0,0,0
2,id_000a6266a,trt_cp,48,D1,0.6280,0.5817,1.5540,-0.0764,-0.0323,1.2390,...,0,0,0,0,0,0,0,0,0,0
3,id_0015fd391,trt_cp,48,D1,-0.5138,-0.2491,-0.2656,0.5288,4.0620,-0.8095,...,0,0,0,0,0,0,0,0,0,0
4,id_001626bd3,trt_cp,72,D2,-0.3254,-0.4009,0.9700,0.6919,1.4180,-0.8244,...,0,0,0,0,0,0,0,0,0,0

# Data Exploration

In [4]:
df.describe(include = 'all')

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
count,23814,23814,23814.000000,23814,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,...,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000
unique,23814,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,id_2ec8bdca3,trt_cp,NaN,D1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,21948,NaN,12147,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.020156,NaN,0.248366,-0.095684,0.152253,0.081971,0.057347,-0.138836,...,0.000252,0.001050,0.002016,0.013270,0.003065,0.000252,0.007139,0.001092,0.001638,0.001260
std,NaN,NaN,19.402807,NaN,1.393399,0.812363,1.035731,0.950012,1.032091,1.179388,...,0.015871,0.032384,0.044851,0.114429,0.055283,0.015871,0.084190,0.033025,0.040436,0.035472
min,NaN,NaN,24.000000,NaN,-5.513000,-5.737000,-9.104000,-5.998000,-6.369000,-10.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,24.000000,NaN,-0.473075,-0.562200,-0.437750,-0.429575,-0.470925,-0.602225,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,48.000000,NaN,-0.008850,-0.046600,0.075200,0.008050,-0.026900,-0.015650,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,72.000000,NaN,0.525700,0.403075,0.663925,0.463400,0.465375,0.510425,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,72.000000,NaN,10.000000,5.039000,8.257000,10.000000,10.000000,7.282000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
df[train_y_scored.columns].describe(include = 'all')

,sig_id,5-alpha_reductase_inhibitor,11-beta-hsd1_inhibitor,acat_inhibitor,acetylcholine_receptor_agonist,acetylcholine_receptor_antagonist,acetylcholinesterase_inhibitor,adenosine_receptor_agonist,adenosine_receptor_antagonist,adenylyl_cyclase_activator,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
count,23814,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,...,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000,23814.000000
unique,23814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,id_2ec8bdca3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.000714,0.000756,0.001008,0.007979,0.012640,0.003065,0.002268,0.004031,0.000504,...,0.000252,0.001050,0.002016,0.013270,0.003065,0.000252,0.007139,0.001092,0.001638,0.001260
std,NaN,0.026709,0.027483,0.031731,0.088967,0.111716,0.055283,0.047566,0.063365,0.022443,...,0.015871,0.032384,0.044851,0.114429,0.055283,0.015871,0.084190,0.033025,0.040436,0.035472
min,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df[df.drop(columns=['Result']).eq(0).any(axis=1)]

In [7]:
temp = df[train_y_scored.columns].sum(axis=1)
idx = temp[temp == 0].index
df[df.index.isin(idx)].describe(include = 'all')

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
count,9367,9367,9367.000000,9367,9367.000000,9367.000000,9367.000000,9367.000000,9367.000000,9367.000000,...,9367.0,9367.0,9367.0,9367.0,9367.0,9367.0,9367.0,9367.0,9367.0,9367.0
unique,9367,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,id_f90937b7e,trt_cp,NaN,D1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,7501,NaN,4775,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.015373,NaN,0.017800,-0.126930,0.113188,-0.006959,-0.050937,-0.084490,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,NaN,19.390845,NaN,0.961864,0.786366,1.015517,0.811233,0.918677,1.115484,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,NaN,NaN,24.000000,NaN,-5.261000,-3.523000,-9.104000,-5.998000,-6.369000,-10.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,NaN,NaN,24.000000,NaN,-0.524250,-0.577200,-0.471750,-0.460100,-0.522400,-0.539650,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,NaN,NaN,48.000000,NaN,-0.070600,-0.066600,0.039100,-0.029600,-0.074400,0.005100,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,NaN,NaN,72.000000,NaN,0.412050,0.372900,0.616450,0.395400,0.395550,0.535300,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,NaN,NaN,72.000000,NaN,9.908000,5.039000,6.207000,10.000000,6.511000,6.904000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
idx

Int64Index([    1,     3,     6,     8,    14,    25,    30,    31,    33,
               35,
            ...
            23788, 23790, 23792, 23793, 23795, 23801, 23804, 23806, 23811,
            23813],
           dtype='int64', length=9367)

In [10]:
df.cp_type.value_counts()

trt_cp         21948
ctl_vehicle     1866
Name: cp_type, dtype: int64

In [11]:
df[df.cp_type == "ctl_vehicle"]

,sig_id,cp_type,cp_time,cp_dose,g-0,g-1,g-2,g-3,g-4,g-5,...,tropomyosin_receptor_kinase_inhibitor,trpv_agonist,trpv_antagonist,tubulin_inhibitor,tyrosine_kinase_inhibitor,ubiquitin_specific_protease_inhibitor,vegfr_inhibitor,vitamin_b,vitamin_d_receptor_agonist,wnt_inhibitor
25,id_0054388ec,ctl_vehicle,48,D1,-0.6696,-0.2718,-1.2230,-0.6226,-0.7220,0.1588,...,0,0,0,0,0,0,0,0,0,0
38,id_0079af0fb,ctl_vehicle,24,D1,-0.1636,-1.8230,-0.5211,0.3054,-1.1280,0.6041,...,0,0,0,0,0,0,0,0,0,0
40,id_007bfbb91,ctl_vehicle,24,D2,-1.3200,-1.7340,-0.0741,1.5440,-1.8290,-0.0951,...,0,0,0,0,0,0,0,0,0,0
47,id_008a986b7,ctl_vehicle,48,D2,0.4860,0.1430,0.5281,-0.0022,-0.2334,-0.6607,...,0,0,0,0,0,0,0,0,0,0
63,id_009d8340f,ctl_vehicle,24,D2,0.4471,-0.0839,-0.3864,0.3196,0.2584,-0.3156,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23729,id_ff1f9e5fc,ctl_vehicle,24,D1,0.0465,0.6430,-0.2453,0.3521,0.6195,-0.6659,...,0,0,0,0,0,0,0,0,0,0
23747,id_ff469c482,ctl_vehicle,72,D1,-0.6204,-1.3800,-1.1880,-0.6573,-0.8408,-0.2447,...,0,0,0,0,0,0,0,0,0,0
23768,id_ff89331ca,ctl_vehicle,72,D2,-0.1051,0.4335,0.3648,-0.0525,-0.3632,-0.3228,...,0,0,0,0,0,0,0,0,0,0
23793,id_ffd26f361,ctl_vehicle,48,D2,0.6008,0.2781,-0.3319,-0.8782,0.9281,0.7535,...,0,0,0,0,0,0,0,0,0,0
23811,id_fffc1c3f4,ctl_vehicle,48,D2,0.3942,0.3756,0.3109,-0.7389,0.5505,-0.0159,...,0,0,0,0,0,0,0,0,0,0

# Model Building